### ISSUE TITLE
Workflow with the SVCD normalization and a DESeq test for RNA-seq

### ISSUE THREAD

**Issue by michaelpierrelee** [carlosproca/cdnormbio#4]
Dear Dr. Roca,
After reading your paper, I'm testing your normalization method in a RNA-seq experiment. I would like to have your opinion on my workflow:
1. normalize by SVCD on log2-scaled counts,
2. remove non expressed genes from the table,
3. estimate variance dispersion* by DESeq package,
4. apply negative binomial test** (the transformed normalized factors from SVCD are used as size factors),
5. remove the lowest expressed genes by an independent filtering based on the overall sum of normalized counts,
6. apply a 2nd test.

There are around 20000 transcripts from a microalgae in 4 different conditions to compare, with 3 replicates per condition.
Best regards

*https://www.rdocumentation.org/packages/DESeq/versions/1.24.0/topics/estimateDispersions
**https://www.rdocumentation.org/packages/DESeq/versions/1.24.0/topics/nbinomTest

**Comment by carlosproca** [comment]
Hi Michael, 

I agree with the main approach of your pipeline. I understand that you want to use DESeq to analyze differential expression, but using the normalization factors from SVCD normalization as size factors for DESeq. An important detail with RNA-Seq is how to deal with low-count genes.

Are you using the DESeq package instead of the updated version DESeq2 for any particular reason? With DESeq2, a [simple analysis](http://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#quick-start) would be:
```R
library( DESeq2 )

dds <- DESeqDataSetFromMatrix( count.data, sample.data, design )
dds <- DESeq( dds )
res <- results( dds )
```

To [override the size factors](http://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#sample-gene-dependent-normalization-factors) calculated by `DESeq()`:
```R
library( DESeq2 )

other.size.factors <- calculate.size.factor( count.data, ... )

dds <- DESeqDataSetFromMatrix( count.data, sample.data, design )
sizeFactors( dds ) <- other.size.factors
dds <- DESeq( dds )
res <- results( dds )
```

Concerning the issue of low-count genes, a robust approach is to only use genes with medium-to-high counts for SVCD normalization. As each size factor affects equally all genes in the corresponding sample, using a subset of genes does not bias the calculation. The drawback is an increase in the estimation error. However, for the number of genes usually available, this error would still be very low. This also avoids using more sophisticated methods to [change to log2 scale](http://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#count-data-transformations).

Following with the previous example:
```R
library( DESeq2 )
library( cdnormbio )

expr.data <- count.data[ rowMin( count.data ) >= 1 & rowMeans( count.data ) >= 10, ]
expr.data <- log2( expr.data )
normalize.result <- normalize.svcd( expr.data, expr.condition )
svcd.size.factors <- 2^normalize.result$offset

dds <- DESeqDataSetFromMatrix( count.data, sample.data, design )
sizeFactors( dds ) <- svcd.size.factors
dds <- DESeq( dds )
res <- results( dds )
```

One way to verify that SVCD normalization works well with DESeq is to compare the size factors obtained from a synthetic dataset with negative binomial data. Given that `makeExampleDESeqDataSet()` does not introduce (by default) differential expression between conditions, both methods should yield similarly good results. Using an experiment design like yours:
```R
library( DESeq2 )
library( cdnormbio )

true.size.factors <- rnorm( 12 )
true.size.factors <- 2^( true.size.factors - mean( true.size.factors ) )
dds <- makeExampleDESeqDataSet( 20000, 12, sizeFactors = true.size.factors )
dds$condition <- factor( rep( c( "a", "b", "c", "d" ), each=3 ) )

count.data <- assay( dds )
expr.data <- count.data[ rowMin( count.data ) >= 1 & rowMeans( count.data ) >= 10, ]
expr.data <- log2( expr.data )
normalize.result <- normalize.svcd( expr.data, dds$condition, verbose = TRUE )
svcd.size.factors <- 2^normalize.result$offset

dds <- estimateSizeFactors( dds )
deseq.size.factors <- sizeFactors( dds )

plot( true.size.factors, cex=1.5 )
points( svcd.size.factors, pch=20, col="blue" )
points( deseq.size.factors, pch=20, col="red" )
```

I hope this helps. If you have more questions, I am happy to help. I wish you good progress with your analyses, and many thanks for using these normalization methods.
